project:
  type: website
  output-dir: docs

resources:
  - resume/**
  - docs/*.pdf

website:
  title: "STA 9750 Submission Material"
  description:
    Course Projects for STA 9750 at Baruch College
  site-url: "https://Helly101-1.github.io/STA9750-2026-SPRING/"
  navbar:
    background: primary
    search: false

format:
  html:
    theme: sandstone
    toc: false

editor:
  mode: source
